default: &default
  adapter: postgresql
  encoding: unicode
  username: development
  password: development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ymir_development

test:
  <<: *default
  database: ymir_test

production:
  <<: *default
  database: ymir_production
  username: ymir
  password: <%= ENV['RAILS-REACT-HEROKU_DATABASE_PASSWORD'] %>
